Добавлен сундук
mc-modding/forge-example pull request #7
Opened 2022-08-30 16:28 UTC by TheAndrey

Добавлен сундук на 63 слота как пример для статей про инвентарь, контейнер и Gui. Внешне выглядит как в бетках. Код пока без комментов, предлагаю на ревью.

2022-08-30 18:20 UTC, Icosider requested changes

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/CommonProxy.java
> +        switch (id) {
Можно без id, проверять по тайлу и открывать окно.

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    private IIcon iconTop, iconSide, iconFront;
Не надо так делать, это выглядит странно. Я бы в начале писал name, а потом Icon, чтобы было `nameIcon`

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +        setBlockName("mcmodding.chest");
Если делать, то не только для сундука, но и для всех.

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    @SideOnly(Side.CLIENT)
Можно было запихнуть под @Override аннотацию

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +                    chest.setInventorySlotContents(slot, null);
Не надо так делать, для таких действий, есть `IInventory#getStackInSlotOnClosing`, вместо `IInventory#getStackInSlot`(при должной реализации)

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/container/ChestContainer.java
> +            for (int col = 0; col < 9; col++) {
Что за `col`? Я думаю стоит сделать `column`

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        return items[slot];
Нет проверки на то, что слот находится в допустимом диапазоне для массива. `slot >= 0 && slot < items.size`

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +    public ItemStack decrStackSize(int slot, int amount) {
Можно лучше реализовать

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +    public ItemStack getStackInSlotOnClosing(int slot) {
```java
ItemStack stackInSlot = getStackInSlot(slotId);
if (stackInSlot != null) {
    setInventorySlotContents(slotId, null);
}
return stackInSlot;
```

2022-08-30 18:20 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        Arrays.fill(items, null); // Очищаем слоты на случай перезагрузки данных из NBT
Эффективней создать новый массив

2022-08-30 18:25 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/CommonProxy.java
> +        switch (id) {
Бред. ID указывается чтобы понять, чей GUI хотим открыть. Всё же instanceof дорогая операция.

2022-08-30 18:26 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/CommonProxy.java
> +        switch (id) {
Я не говорил про instanceof

2022-08-30 18:26 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    private IIcon iconTop, iconSide, iconFront;
Мне, например, не нравится текущее именование классов объектов. Лучше когда Block на начале названия, это лучше для сортировки по имени когда в пакете много классов.

2022-08-30 18:28 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +        setBlockName("mcmodding.chest");
Мод не мой ¯\\\_(ツ)\_/¯

2022-08-30 18:29 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    private IIcon iconTop, iconSide, iconFront;
Вообще, по code style, необходимо название родительского класса отображать в конце названия наследника, а в данном случае кое-кто из MCP накосячил. В итоге только в 1.14 нормальные названия появились.

2022-08-30 18:29 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    @SideOnly(Side.CLIENT)
Некогда было смотреть на такие мелочи. Работоспособность стоит на первом месте.

2022-08-30 18:29 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +                    chest.setInventorySlotContents(slot, null);
Вкусовщина, чисто ради 0.0001% производительности.

2022-08-30 18:31 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +                    chest.setInventorySlotContents(slot, null);
Не ради производительности, а потому что многие при дропе из блока даже `IInventory#setInventorySlotContents` не делают, но опять же, чтобы не городить свои костыли, был написан специальный метод для таких действий.

2022-08-30 18:31 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        return items[slot];
Никто над этим вообще не заморачивается и за много лет крашей на этом месте не встречал. Такая проверка реально для meta/damage нужна, где у игрока есть простор добыть багованный предмет.

2022-08-30 18:32 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        return items[slot];
Если не попадались такие баги, то это не значит, что их нет и не будет, по большей части моды друг-друга ломают...

2022-08-30 18:33 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +    public ItemStack getStackInSlotOnClosing(int slot) {
А разница? Проверять JVM, переопределён ли вызваемый метод, чем прямо "в лоб" изменить значение массива без лишних телодвижений.

2022-08-30 18:35 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        Arrays.fill(items, null); // Очищаем слоты на случай перезагрузки данных из NBT
Бережно отношусь к памяти. Увы, не создать - поле у нас final.

2022-08-30 18:36 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +    public ItemStack getStackInSlotOnClosing(int slot) {
Так красивей, а вообще, лучше стараться минимизировать кол-во получений из массива, даже с учётом того, что это O(1)

2022-08-30 18:38 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        Arrays.fill(items, null); // Очищаем слоты на случай перезагрузки данных из NBT
Если уж зашла речь про экономию памяти, то можно в принципе использовать всякие WeakReference и т.п. :)

2022-08-30 18:39 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    private IIcon iconTop, iconSide, iconFront;
Официальные маппинги, они такие официальные...
На наследование `BlockContainer` можно было забить, волшебства для работы с тайлами там никакого нет. Этот класс необязательный.

2022-08-30 18:40 UTC, Icosider commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    private IIcon iconTop, iconSide, iconFront;
А при чём здесь `BlockContainer`?

2022-08-30 18:41 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +                    chest.setInventorySlotContents(slot, null);
Не сказать что сильно нужный метод, как и бестолковый `isUseableByPlayer()`.

2022-08-30 18:43 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        return items[slot];
Может один 0.1% таких модов попадался. Проще вылечить один проблемный, чем перелопачивать сотню других на добавление валидации индекса.

2022-08-30 18:45 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +    public ItemStack getStackInSlotOnClosing(int slot) {
Была идея улучшить, потом передумал чтобы новичков не путать.

2022-08-30 18:53 UTC, TheAndrey commented
Если сильно фокусироваться на всякой мелочёвке, никак не влияющей на качество, **скорость написания очень сильно страдает** 📉

**Предлагаю следующие варианты:**
- Меньше обращать внимания на мелочи, лить как есть. Проверку кода ограничить поиском багов/крашей/дюпов.
- Если для тебя код-стайл имеет большое значение, разрешаю переделать на свой лад молча, **не спрашивая меня**. Проект не мой и мне всё равно что с ним будет.

2022-08-30 18:58 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/block/ChestBlock.java
> +    private IIcon iconTop, iconSide, iconFront;
Про именование. Как ловко обойти:

> по code style, необходимо название родительского класса отображать в конце названия наследника

2022-08-30 19:00 UTC, TheAndrey commented on src/main/java/ru/mcmodding/tutorial/common/tile/ChestTile.java
> +        Arrays.fill(items, null); // Очищаем слоты на случай перезагрузки данных из NBT
Мягкие ссылки - это уже другая история, про то как не мешать объектам выгружаться из памяти (тайлы, ентити и прочие).

2022-08-31 08:41 UTC, Icosider approved these changes

2022-08-31 08:45 UTC, merged